---
- hosts: matrixbots
  become: true
  become_method: sudo

  vars:
    ipa_admin_user: admin
    ipa_admin_password: password
    krb_realm: TINYSTAGE.TEST

  roles:
    - common
    - ipa-client
    - synapse
    - nginx
    - maubot
    - mote
    - chatenv